runs:
  using: "composite"
  description: "Set credentials for NuGet & GitHub packages"
  inputs:
    api-key-github:
      required: true
      description: "GitHub API key"
    api-user-github:
      required: true
      description: "GitHub API user"
    api-key-nuget:
      required: true
      description: "NuGet API key"
    api-user-nuget:
      required: true
      description: "NuGet API user"

  steps:
    - name: NuGet - Update credentials
      run: |
        (cd ../.. && dotnet new nugetconfig --force)
        dotnet nuget remove source local > /dev/null || :
        dotnet nuget remove source local.ci > /dev/null || :
        dotnet nuget remove source github > /dev/null || :
        dotnet nuget remove source nuget.org > /dev/null || :
        dotnet nuget add source https://nuget.pkg.github.com/MaxRev-Dev/index.json --name github --store-password-in-clear-text -u ${{ inputs.api-user-github }} -p ${{ inputs.api-key-github }} --configfile ../nuget.config
        dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org --store-password-in-clear-text -u ${{ inputs.api-user-nuget }} -p ${{ inputs.api-key-nuget }} --configfile ../nuget.config