# GDAL.NETCORE Builder - A lightweight test image for vcpkg package installations

FROM debian:12 as base

RUN apt-get update && apt-get install -y \
    build-essential gnupg \
    curl zip unzip tar git wget \
    pkg-config \
    ninja-build \
    autoconf libtool autoconf-archive libudev-dev libpcre2-dev \
    python3 python3-pip \
    linux-libc-dev \
    libhdf4-dev libnetcdf-dev linux-libc-dev \
    patchelf

COPY ci/install-swig-unix.sh /tmp/install-swig-unix.sh
RUN chmod +x /tmp/install-swig-unix.sh && \
    SWIG_INSTALL_PREFIX=/usr/local /tmp/install-swig-unix.sh

# install cmake latest (--break-system-packages: PEP 668 on bookworm)
RUN pip install cmake --upgrade --break-system-packages

# vcpkg repo (change to your local clone of vcpkg)
COPY ci/cache*/vcpkg-archives* /vcpkg-archives/
COPY ci/cache*/build*/vcpkg* /vcpkg/
RUN ls -la /vcpkg-archives/
RUN ls -la /vcpkg/
ARG VCPKG_DEFAULT_BINARY_CACHE=/vcpkg-archives/

WORKDIR /vcpkg

# default build args
ARG BUILD_ARCH=arm64
ARG LINKAGE=dynamic

ENV VCPKG_FORCE_SYSTEM_BINARIES=1
RUN ./bootstrap-vcpkg.sh 

RUN mkdir -p custom-triplets && echo " \
set(VCPKG_TARGET_ARCHITECTURE ${BUILD_ARCH})\n \
set(VCPKG_CRT_LINKAGE ${LINKAGE})\n \
set(VCPKG_LIBRARY_LINKAGE ${LINKAGE})\n \
set(VCPKG_BUILD_TYPE release)\n \
set(VCPKG_CMAKE_SYSTEM_NAME Linux)" > custom-triplets/${BUILD_ARCH}-linux.cmake

RUN cat custom-triplets/${BUILD_ARCH}-linux.cmake

RUN ./vcpkg install hdf5:${BUILD_ARCH}-linux  --overlay-triplets=./custom-triplets --editable
